### ISSUE TITLE
Detect correctly whether iPhone has top notch or not

### ISSUE THREAD

**Issue by fxwx23** [fxwx23/Volumizer#8]
To support iPhone XR, XS and XS Max, need to fix the way to detect iPhone X series.
https://github.com/fxwx23/Volumizer/blob/6464919f202b5f505f55504abbf142a86d2fdde0/Volumizer/Volumizer.swift#L303

**Comment by Zandor300** [comment]
You can do that the following way:
```swift
return window.safeAreaInsets.bottom > 0.0 && UIDevice.current.userInterfaceIdiom == .phone
```
Having a bottom slide-up-to-go-home bar means having a notch.

Taken from FTLinearActivityIndicator:
https://github.com/futuretap/FTLinearActivityIndicator/blob/a4f11f81253dab847faa694ed9f1905a5ce88d85/FTLinearActivityIndicator/Classes/UIApplication%2BLinearNetworkActivityIndicator.swift#L15

**Comment by fxwx23** [comment]
Thanks for your advice. :)
